#Requires -Version 7.0
<#
.SYNOPSIS
    Publishes the Automation runbook content for automation-scheduled mode.

.DESCRIPTION
    Azure Automation PowerShell runbooks are deployed as a single script, not a folder, so this
    script concatenates the shared remediation module (the single source of truth also used by the
    Function app and Pester tests) with the thin automation wrapper in src/automation, and uploads
    the result with `az automation runbook replace-content`, which uploads and publishes in one step
    without requiring a public content-hosting URL (unlike ARM/Bicep's publishContentLink).

    Called from scripts/postprovision.ps1 for automation-scheduled mode. Safe to re-run.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $ResourceGroupName,

    [Parameter(Mandatory = $true)]
    [string] $AutomationAccountName,

    [Parameter(Mandatory = $true)]
    [string] $RunbookName
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

if ([string]::IsNullOrWhiteSpace($ResourceGroupName) -or [string]::IsNullOrWhiteSpace($AutomationAccountName)) {
    Write-Warning 'ResourceGroupName or AutomationAccountName is empty; skipping Automation runbook publish. This is expected if AZD_DEPLOYMENT_MODE is not automation-scheduled.'
    return
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$sharedModulePath = Join-Path $repoRoot 'src\shared\EmergencyAccessRemediation.psm1'
$wrapperPath = Join-Path $repoRoot 'src\automation\EmergencyAccessRemediation.ps1'

if (-not (Test-Path $sharedModulePath)) { throw "Shared module not found at $sharedModulePath" }
if (-not (Test-Path $wrapperPath)) { throw "Automation wrapper not found at $wrapperPath" }

Write-Host "Publishing runbook '$RunbookName' in automation account '$AutomationAccountName'..."

$sharedContent = Get-Content -Path $sharedModulePath -Raw
$wrapperContent = Get-Content -Path $wrapperPath -Raw

# Export-ModuleMember is valid in the source .psm1 but not in the generated standalone runbook.
$sharedContent = $sharedContent -replace '(?ms)^Export-ModuleMember\s+-Function\s+@\(.*?^\)\s*$', ''

# Strip the wrapper's own Import-Module guard block reference to the .psm1 path -- once the shared
# module's functions are inlined above the wrapper body, the guard's Get-Command check simply finds
# them already defined and skips re-importing, so no wrapper edits are required here.
$combined = @"
<#
    Combined runbook content, generated by scripts/Publish-AutomationRunbook.ps1.
    Source of truth: src/shared/EmergencyAccessRemediation.psm1 + src/automation/EmergencyAccessRemediation.ps1.
    Do not edit the published runbook directly -- edit the source files and re-run postprovision.
#>

$sharedContent

$wrapperContent
"@

$tempScript = New-TemporaryFile
$tempScriptPath = [System.IO.Path]::ChangeExtension($tempScript.FullName, '.ps1')
Remove-Item $tempScript -ErrorAction SilentlyContinue
Set-Content -Path $tempScriptPath -Value $combined -Encoding utf8NoBOM

try {
    # Validate the combined script parses before uploading.
    $tokens = $null
    $parseErrors = $null
    [System.Management.Automation.Language.Parser]::ParseFile($tempScriptPath, [ref]$tokens, [ref]$parseErrors) | Out-Null
    if ($parseErrors.Count -gt 0) {
        throw "Combined runbook content failed to parse: $($parseErrors[0].Message)"
    }

    az automation runbook replace-content `
        --resource-group $ResourceGroupName `
        --automation-account-name $AutomationAccountName `
        --name $RunbookName `
        --content "@$tempScriptPath" `
        -o none

    if ($LASTEXITCODE -ne 0) {
        throw "az automation runbook replace-content failed with exit code $LASTEXITCODE."
    }

    az automation runbook publish `
        --resource-group $ResourceGroupName `
        --automation-account-name $AutomationAccountName `
        --name $RunbookName `
        -o none

    if ($LASTEXITCODE -ne 0) {
        throw "az automation runbook publish failed with exit code $LASTEXITCODE."
    }

    Write-Host "Runbook '$RunbookName' published successfully." -ForegroundColor Green
}
finally {
    Remove-Item -Path $tempScriptPath -ErrorAction SilentlyContinue
}
