name: azd catalog metadata

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  catalog:
    name: azd catalog metadata
    uses: nathanmcnulty/azd-reference/.github/workflows/catalog-metadata.yml@3db9d264c7ee4464826058191a689b23a30b980c
    permissions:
      contents: read
